# Generated by Django 4.1.7 on 2023-03-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="productMainModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=30)),
                ("Description", models.CharField(max_length=30)),
                ("Unique_id", models.CharField(max_length=30)),
                ("Price", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="userModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Phone_number", models.CharField(max_length=30, unique=True)),
                ("Email", models.EmailField(max_length=254)),
                ("is_customer", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="userProfile",
            fields=[
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app_assignment.usermodel",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Date_of_birth", models.CharField(max_length=30)),
                ("Gender", models.CharField(max_length=30)),
                ("Image", models.ImageField(upload_to="uploads/")),
            ],
        ),
        migrations.CreateModel(
            name="userloginotpModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Otp", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_assignment.usermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCartProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[(1, "Pending"), (2, "Completed")],
                        default="1",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_assignment.usermodel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_assignment.productmainmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="productImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_assignment.productmainmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserCartModel",
            fields=[
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="app_assignment.usermodel",
                    ),
                ),
                ("price", models.CharField(max_length=30)),
                (
                    "products",
                    models.ManyToManyField(to="app_assignment.usercartproductmodel"),
                ),
            ],
        ),
    ]
